Revert back to SQLAlchemy before 1.4.
It breaks with:
    class BuildbotEngineStrategy(strategies.PlainEngineStrategy):
    AttributeError: module 'sqlalchemy.engine.strategies' has no attribute 'PlainEngineStrategy'